bodies:
 - Env:
     type: simple
     is_static: true
     default_tag_size: 0.2
     pose:
       position:
         x: 0.00000000
         y: -0.00000000
         z: 0.00000000
       rotation:
         x: 0.00000000
         y: 0.00000000
         z: 0.00000000
       position_noise:
         x: 0.00010000
         y: 0.00010000
         z: 0.00010000
       rotation_noise:
         x: 0.00001000
         y: 0.00001000
         z: 0.00001000
     tags:
       - id: 0
         size: 0.20000000
         pose:
           position:
             x: 0.00000000
             y: 0.00000000
             z: 0.00000000
           rotation:
             x: 0.00000000
             y: 0.00000000
             z: -0.00000000
           position_noise:
             x: 0.00010000
             y: 0.00010000
             z: 0.00010000
           rotation_noise:
             x: 0.00001000
             y: 0.00001000
             z: 0.00001000
       - id: 14
         size: 0.20000000
         pose:
           position:
             x: -0.46058995
             y: -1.00646351
             z: -0.00466322
           rotation:
             x: 0.04063459
             y: -0.05776737
             z: 0.00155859
           position_noise:
             x: 0.00050055
             y: 0.00038941
             z: 0.00149254
           rotation_noise:
             x: 0.00497159
             y: 0.00509334
             z: 0.00072715
       - id: 16
         size: 0.20000000
         pose:
           position:
             x: 0.99347968
             y: 0.54128468
             z: -0.00089449
           rotation:
             x: -0.00264179
             y: 0.01993658
             z: 0.01161336
           position_noise:
             x: 0.00067610
             y: 0.00065565
             z: 0.00142897
           rotation_noise:
             x: 0.00187130
             y: 0.00184338
             z: 0.00100283
       - id: 1
         size: 0.20000000
         pose:
           position:
             x: 0.47743835
             y: 0.53491713
             z: -0.00331257
           rotation:
             x: 0.00412611
             y: 0.02167631
             z: 0.00929344
           position_noise:
             x: 0.00035240
             y: 0.00041712
             z: 0.00091848
           rotation_noise:
             x: 0.00176626
             y: 0.00180287
             z: 0.00082205
       - id: 21
         size: 0.20000000
         pose:
           position:
             x: 0.99821541
             y: 0.03213800
             z: 0.00676382
           rotation:
             x: -0.00611114
             y: 0.01955368
             z: -0.00106272
           position_noise:
             x: 0.00047770
             y: 0.00045718
             z: 0.00121905
           rotation_noise:
             x: 0.00170464
             y: 0.00166726
             z: 0.00085099
       - id: 3
         size: 0.20000000
         pose:
           position:
             x: 0.47546730
             y: 1.01918355
             z: -0.01024918
           rotation:
             x: 0.00405290
             y: 0.03335596
             z: 0.00794618
           position_noise:
             x: 0.00065923
             y: 0.00086526
             z: 0.00143199
           rotation_noise:
             x: 0.00199964
             y: 0.00204491
             z: 0.00118549
       - id: 2
         size: 0.20000000
         pose:
           position:
             x: 0.99621636
             y: 1.00809668
             z: 0.00046830
           rotation:
             x: -0.00592399
             y: 0.02415472
             z: 0.02502461
           position_noise:
             x: 0.00137311
             y: 0.00148184
             z: 0.00217941
           rotation_noise:
             x: 0.00260737
             y: 0.00261794
             z: 0.00167752
       - id: 18
         size: 0.20000000
         pose:
           position:
             x: -0.01010476
             y: 1.01726367
             z: -0.01180230
           rotation:
             x: -0.00911694
             y: -0.00258857
             z: 0.00930933
           position_noise:
             x: 0.00047298
             y: 0.00068720
             z: 0.00125716
           rotation_noise:
             x: 0.00172119
             y: 0.00182359
             z: 0.00098822
       - id: 6
         size: 0.20000000
         pose:
           position:
             x: -0.47922533
             y: 0.53614577
             z: -0.01706267
           rotation:
             x: 0.00807479
             y: -0.02390918
             z: 0.00108954
           position_noise:
             x: 0.00030472
             y: 0.00047032
             z: 0.00097357
           rotation_noise:
             x: 0.00182891
             y: 0.00207856
             z: 0.00094108
       - id: 4
         size: 0.20000000
         pose:
           position:
             x: -0.50049874
             y: 1.02000930
             z: -0.01656697
           rotation:
             x: 0.00060193
             y: -0.00939654
             z: -0.00408652
           position_noise:
             x: 0.00047853
             y: 0.00104071
             z: 0.00159241
           rotation_noise:
             x: 0.00209708
             y: 0.00226290
             z: 0.00124458
       - id: 5
         size: 0.20000000
         pose:
           position:
             x: -1.01210283
             y: 1.04100206
             z: -0.05942801
           rotation:
             x: 0.00341977
             y: -0.05326961
             z: -0.00598139
           position_noise:
             x: 0.00088854
             y: 0.00185968
             z: 0.00253704
           rotation_noise:
             x: 0.00263747
             y: 0.00266463
             z: 0.00153108
       - id: 7
         size: 0.20000000
         pose:
           position:
             x: -0.99834952
             y: 0.58202938
             z: -0.03517131
           rotation:
             x: 0.01042181
             y: -0.03431814
             z: 0.01913620
           position_noise:
             x: 0.00041804
             y: 0.00073680
             z: 0.00150268
           rotation_noise:
             x: 0.00202181
             y: 0.00218271
             z: 0.00109521
       - id: 20
         size: 0.20000000
         pose:
           position:
             x: -0.99506760
             y: 0.00381912
             z: -0.03061911
           rotation:
             x: 0.01105345
             y: -0.03209210
             z: -0.00350312
           position_noise:
             x: 0.00031146
             y: 0.00052686
             z: 0.00124945
           rotation_noise:
             x: 0.00193708
             y: 0.00211289
             z: 0.00086865
       - id: 10
         size: 0.20000000
         pose:
           position:
             x: -0.99460301
             y: -0.46159338
             z: -0.02293130
           rotation:
             x: 0.00711097
             y: -0.05735600
             z: 0.00759575
           position_noise:
             x: 0.00036309
             y: 0.00055638
             z: 0.00139608
           rotation_noise:
             x: 0.00196130
             y: 0.00206569
             z: 0.00076415
       - id: 9
         size: 0.20000000
         pose:
           position:
             x: -0.47950194
             y: -0.43381618
             z: -0.00414215
           rotation:
             x: 0.01561338
             y: -0.03702621
             z: 0.03477436
           position_noise:
             x: 0.00027763
             y: 0.00038757
             z: 0.00089046
           rotation_noise:
             x: 0.00178863
             y: 0.00202520
             z: 0.00071559
       - id: 15
         size: 0.20000000
         pose:
           position:
             x: -1.00299475
             y: -1.01982685
             z: -0.03112640
           rotation:
             x: 0.06414392
             y: -0.07076278
             z: 0.02086586
           position_noise:
             x: 0.00062010
             y: 0.00054698
             z: 0.00199214
           rotation_noise:
             x: 0.00358220
             y: 0.00330834
             z: 0.00098492
       - id: 19
         size: 0.20000000
         pose:
           position:
             x: 0.00969441
             y: -1.01392882
             z: 0.00768195
           rotation:
             x: 0.03683745
             y: 0.00395258
             z: 0.00901776
           position_noise:
             x: 0.00054730
             y: 0.00034541
             z: 0.00148451
           rotation_noise:
             x: 0.00303966
             y: 0.00281133
             z: 0.00079196
       - id: 11
         size: 0.20000000
         pose:
           position:
             x: 0.47117398
             y: -0.45804699
             z: 0.00817003
           rotation:
             x: 0.00524281
             y: 0.01330697
             z: 0.00279132
           position_noise:
             x: 0.00056892
             y: 0.00059963
             z: 0.00123731
           rotation_noise:
             x: 0.00215695
             y: 0.00216044
             z: 0.00104236
       - id: 13
         size: 0.20000000
         pose:
           position:
             x: 0.47589223
             y: -0.99230993
             z: 0.01345051
           rotation:
             x: 0.02214824
             y: 0.01393998
             z: -0.00236763
           position_noise:
             x: 0.00083965
             y: 0.00044776
             z: 0.00181812
           rotation_noise:
             x: 0.00285714
             y: 0.00272345
             z: 0.00112037
       - id: 17
         size: 0.20000000
         pose:
           position:
             x: 1.00690293
             y: -0.46085884
             z: 0.00655724
           rotation:
             x: 0.00863585
             y: 0.01097681
             z: 0.02434766
           position_noise:
             x: 0.00142293
             y: 0.00095765
             z: 0.00206082
           rotation_noise:
             x: 0.00269243
             y: 0.00258538
             z: 0.00155396
       - id: 12
         size: 0.20000000
         pose:
           position:
             x: 1.02739441
             y: -0.98679216
             z: 0.00222508
           rotation:
             x: 0.02531279
             y: 0.02561454
             z: 0.01634600
           position_noise:
             x: 0.00182861
             y: 0.00064340
             z: 0.00257521
           rotation_noise:
             x: 0.00309552
             y: 0.00298811
             z: 0.00165927
 - rig:
     type: simple
     is_static: false
     default_tag_size: 0.00000000
     tags:
